//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 03/05/2020 18:05:49
namespace ResourceCatalogApi.Models
{
    /// <summary>
    /// There are no comments for ContainerSingle in the schema.
    /// </summary>
    public partial class ContainerSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<Container>
    {
        /// <summary>
        /// Initialize a new ContainerSingle object.
        /// </summary>
        public ContainerSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new ContainerSingle object.
        /// </summary>
        public ContainerSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new ContainerSingle object.
        /// </summary>
        public ContainerSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<Container> query)
            : base(query) {}

    }
    /// <summary>
    /// There are no comments for Container in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("Id")]
    public partial class Container : global::Microsoft.OData.Client.BaseEntityType
    {
        /// <summary>
        /// Create a new Container object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="containerCount">Initial value of ContainerCount.</param>
        /// <param name="resourceCount">Initial value of ResourceCount.</param>
        /// <param name="dateCreatedUtc">Initial value of DateCreatedUtc.</param>
        /// <param name="timestampUtc">Initial value of TimestampUtc.</param>
        /// <param name="lastUpdatedUtc">Initial value of LastUpdatedUtc.</param>
        /// <param name="resourceTotalSize">Initial value of ResourceTotalSize.</param>
        /// <param name="resourceMinSize">Initial value of ResourceMinSize.</param>
        /// <param name="resourceMaxSize">Initial value of ResourceMaxSize.</param>
        /// <param name="resourceMeanSize">Initial value of ResourceMeanSize.</param>
        /// <param name="resourceTotalChangedCount">Initial value of ResourceTotalChangedCount.</param>
        /// <param name="resourceMeanChangedCount">Initial value of ResourceMeanChangedCount.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public static Container CreateContainer(int ID, 
                    int containerCount, 
                    int resourceCount, 
                    global::System.DateTimeOffset dateCreatedUtc, 
                    global::System.DateTimeOffset timestampUtc, 
                    global::System.DateTimeOffset lastUpdatedUtc, 
                    long resourceTotalSize, 
                    long resourceMinSize, 
                    long resourceMaxSize, 
                    long resourceMeanSize, 
                    int resourceTotalChangedCount, 
                    double resourceMeanChangedCount)
        {
            Container container = new Container();
            container.Id = ID;
            container.ContainerCount = containerCount;
            container.ResourceCount = resourceCount;
            container.DateCreatedUtc = dateCreatedUtc;
            container.TimestampUtc = timestampUtc;
            container.LastUpdatedUtc = lastUpdatedUtc;
            container.ResourceTotalSize = resourceTotalSize;
            container.ResourceMinSize = resourceMinSize;
            container.ResourceMaxSize = resourceMaxSize;
            container.ResourceMeanSize = resourceMeanSize;
            container.ResourceTotalChangedCount = resourceTotalChangedCount;
            container.ResourceMeanChangedCount = resourceMeanChangedCount;
            return container;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property TenantId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string TenantId
        {
            get
            {
                return this._TenantId;
            }
            set
            {
                this.OnTenantIdChanging(value);
                this._TenantId = value;
                this.OnTenantIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _TenantId;
        partial void OnTenantIdChanging(string value);
        partial void OnTenantIdChanged();
        /// <summary>
        /// There are no comments for Property Path in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string Path
        {
            get
            {
                return this._Path;
            }
            set
            {
                this.OnPathChanging(value);
                this._Path = value;
                this.OnPathChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Path;
        partial void OnPathChanging(string value);
        partial void OnPathChanged();
        /// <summary>
        /// There are no comments for Property Hash in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string Hash
        {
            get
            {
                return this._Hash;
            }
            set
            {
                this.OnHashChanging(value);
                this._Hash = value;
                this.OnHashChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Hash;
        partial void OnHashChanging(string value);
        partial void OnHashChanged();
        /// <summary>
        /// There are no comments for Property ParentPath in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string ParentPath
        {
            get
            {
                return this._ParentPath;
            }
            set
            {
                this.OnParentPathChanging(value);
                this._ParentPath = value;
                this.OnParentPathChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _ParentPath;
        partial void OnParentPathChanging(string value);
        partial void OnParentPathChanged();
        /// <summary>
        /// There are no comments for Property ParentHash in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string ParentHash
        {
            get
            {
                return this._ParentHash;
            }
            set
            {
                this.OnParentHashChanging(value);
                this._ParentHash = value;
                this.OnParentHashChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _ParentHash;
        partial void OnParentHashChanging(string value);
        partial void OnParentHashChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property ContainerCount in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual int ContainerCount
        {
            get
            {
                return this._ContainerCount;
            }
            set
            {
                this.OnContainerCountChanging(value);
                this._ContainerCount = value;
                this.OnContainerCountChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private int _ContainerCount;
        partial void OnContainerCountChanging(int value);
        partial void OnContainerCountChanged();
        /// <summary>
        /// There are no comments for Property ResourceCount in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual int ResourceCount
        {
            get
            {
                return this._ResourceCount;
            }
            set
            {
                this.OnResourceCountChanging(value);
                this._ResourceCount = value;
                this.OnResourceCountChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private int _ResourceCount;
        partial void OnResourceCountChanging(int value);
        partial void OnResourceCountChanged();
        /// <summary>
        /// There are no comments for Property DateCreatedUtc in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.DateTimeOffset DateCreatedUtc
        {
            get
            {
                return this._DateCreatedUtc;
            }
            set
            {
                this.OnDateCreatedUtcChanging(value);
                this._DateCreatedUtc = value;
                this.OnDateCreatedUtcChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.DateTimeOffset _DateCreatedUtc;
        partial void OnDateCreatedUtcChanging(global::System.DateTimeOffset value);
        partial void OnDateCreatedUtcChanged();
        /// <summary>
        /// There are no comments for Property DateModifiedUtc in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.DateTimeOffset> DateModifiedUtc
        {
            get
            {
                return this._DateModifiedUtc;
            }
            set
            {
                this.OnDateModifiedUtcChanging(value);
                this._DateModifiedUtc = value;
                this.OnDateModifiedUtcChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.DateTimeOffset> _DateModifiedUtc;
        partial void OnDateModifiedUtcChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnDateModifiedUtcChanged();
        /// <summary>
        /// There are no comments for Property DateLastAccessedUtc in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.DateTimeOffset> DateLastAccessedUtc
        {
            get
            {
                return this._DateLastAccessedUtc;
            }
            set
            {
                this.OnDateLastAccessedUtcChanging(value);
                this._DateLastAccessedUtc = value;
                this.OnDateLastAccessedUtcChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.DateTimeOffset> _DateLastAccessedUtc;
        partial void OnDateLastAccessedUtcChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnDateLastAccessedUtcChanged();
        /// <summary>
        /// There are no comments for Property TimezoneId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string TimezoneId
        {
            get
            {
                return this._TimezoneId;
            }
            set
            {
                this.OnTimezoneIdChanging(value);
                this._TimezoneId = value;
                this.OnTimezoneIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _TimezoneId;
        partial void OnTimezoneIdChanging(string value);
        partial void OnTimezoneIdChanged();
        /// <summary>
        /// There are no comments for Property TimestampUtc in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.DateTimeOffset TimestampUtc
        {
            get
            {
                return this._TimestampUtc;
            }
            set
            {
                this.OnTimestampUtcChanging(value);
                this._TimestampUtc = value;
                this.OnTimestampUtcChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.DateTimeOffset _TimestampUtc;
        partial void OnTimestampUtcChanging(global::System.DateTimeOffset value);
        partial void OnTimestampUtcChanged();
        /// <summary>
        /// There are no comments for Property LastUpdatedUtc in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.DateTimeOffset LastUpdatedUtc
        {
            get
            {
                return this._LastUpdatedUtc;
            }
            set
            {
                this.OnLastUpdatedUtcChanging(value);
                this._LastUpdatedUtc = value;
                this.OnLastUpdatedUtcChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.DateTimeOffset _LastUpdatedUtc;
        partial void OnLastUpdatedUtcChanging(global::System.DateTimeOffset value);
        partial void OnLastUpdatedUtcChanged();
        /// <summary>
        /// There are no comments for Property ResourceTotalSize in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual long ResourceTotalSize
        {
            get
            {
                return this._ResourceTotalSize;
            }
            set
            {
                this.OnResourceTotalSizeChanging(value);
                this._ResourceTotalSize = value;
                this.OnResourceTotalSizeChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private long _ResourceTotalSize;
        partial void OnResourceTotalSizeChanging(long value);
        partial void OnResourceTotalSizeChanged();
        /// <summary>
        /// There are no comments for Property ResourceMinSize in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual long ResourceMinSize
        {
            get
            {
                return this._ResourceMinSize;
            }
            set
            {
                this.OnResourceMinSizeChanging(value);
                this._ResourceMinSize = value;
                this.OnResourceMinSizeChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private long _ResourceMinSize;
        partial void OnResourceMinSizeChanging(long value);
        partial void OnResourceMinSizeChanged();
        /// <summary>
        /// There are no comments for Property ResourceMaxSize in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual long ResourceMaxSize
        {
            get
            {
                return this._ResourceMaxSize;
            }
            set
            {
                this.OnResourceMaxSizeChanging(value);
                this._ResourceMaxSize = value;
                this.OnResourceMaxSizeChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private long _ResourceMaxSize;
        partial void OnResourceMaxSizeChanging(long value);
        partial void OnResourceMaxSizeChanged();
        /// <summary>
        /// There are no comments for Property ResourceMeanSize in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual long ResourceMeanSize
        {
            get
            {
                return this._ResourceMeanSize;
            }
            set
            {
                this.OnResourceMeanSizeChanging(value);
                this._ResourceMeanSize = value;
                this.OnResourceMeanSizeChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private long _ResourceMeanSize;
        partial void OnResourceMeanSizeChanging(long value);
        partial void OnResourceMeanSizeChanged();
        /// <summary>
        /// There are no comments for Property ResourceOldestDateCreatedUtc in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.DateTimeOffset> ResourceOldestDateCreatedUtc
        {
            get
            {
                return this._ResourceOldestDateCreatedUtc;
            }
            set
            {
                this.OnResourceOldestDateCreatedUtcChanging(value);
                this._ResourceOldestDateCreatedUtc = value;
                this.OnResourceOldestDateCreatedUtcChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.DateTimeOffset> _ResourceOldestDateCreatedUtc;
        partial void OnResourceOldestDateCreatedUtcChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnResourceOldestDateCreatedUtcChanged();
        /// <summary>
        /// There are no comments for Property ResourceNewestDateCreatedUtc in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.DateTimeOffset> ResourceNewestDateCreatedUtc
        {
            get
            {
                return this._ResourceNewestDateCreatedUtc;
            }
            set
            {
                this.OnResourceNewestDateCreatedUtcChanging(value);
                this._ResourceNewestDateCreatedUtc = value;
                this.OnResourceNewestDateCreatedUtcChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.DateTimeOffset> _ResourceNewestDateCreatedUtc;
        partial void OnResourceNewestDateCreatedUtcChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnResourceNewestDateCreatedUtcChanged();
        /// <summary>
        /// There are no comments for Property ResourceMeanDateCreatedUtc in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.DateTimeOffset> ResourceMeanDateCreatedUtc
        {
            get
            {
                return this._ResourceMeanDateCreatedUtc;
            }
            set
            {
                this.OnResourceMeanDateCreatedUtcChanging(value);
                this._ResourceMeanDateCreatedUtc = value;
                this.OnResourceMeanDateCreatedUtcChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.DateTimeOffset> _ResourceMeanDateCreatedUtc;
        partial void OnResourceMeanDateCreatedUtcChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnResourceMeanDateCreatedUtcChanged();
        /// <summary>
        /// There are no comments for Property ResourceOldestDateModifiedUtc in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.DateTimeOffset> ResourceOldestDateModifiedUtc
        {
            get
            {
                return this._ResourceOldestDateModifiedUtc;
            }
            set
            {
                this.OnResourceOldestDateModifiedUtcChanging(value);
                this._ResourceOldestDateModifiedUtc = value;
                this.OnResourceOldestDateModifiedUtcChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.DateTimeOffset> _ResourceOldestDateModifiedUtc;
        partial void OnResourceOldestDateModifiedUtcChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnResourceOldestDateModifiedUtcChanged();
        /// <summary>
        /// There are no comments for Property ResourceNewestDateModifiedUtc in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.DateTimeOffset> ResourceNewestDateModifiedUtc
        {
            get
            {
                return this._ResourceNewestDateModifiedUtc;
            }
            set
            {
                this.OnResourceNewestDateModifiedUtcChanging(value);
                this._ResourceNewestDateModifiedUtc = value;
                this.OnResourceNewestDateModifiedUtcChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.DateTimeOffset> _ResourceNewestDateModifiedUtc;
        partial void OnResourceNewestDateModifiedUtcChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnResourceNewestDateModifiedUtcChanged();
        /// <summary>
        /// There are no comments for Property ResourceMeanDateModifiedUtc in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.DateTimeOffset> ResourceMeanDateModifiedUtc
        {
            get
            {
                return this._ResourceMeanDateModifiedUtc;
            }
            set
            {
                this.OnResourceMeanDateModifiedUtcChanging(value);
                this._ResourceMeanDateModifiedUtc = value;
                this.OnResourceMeanDateModifiedUtcChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.DateTimeOffset> _ResourceMeanDateModifiedUtc;
        partial void OnResourceMeanDateModifiedUtcChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnResourceMeanDateModifiedUtcChanged();
        /// <summary>
        /// There are no comments for Property ResourceOldestDateLastAccessedUtc in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.DateTimeOffset> ResourceOldestDateLastAccessedUtc
        {
            get
            {
                return this._ResourceOldestDateLastAccessedUtc;
            }
            set
            {
                this.OnResourceOldestDateLastAccessedUtcChanging(value);
                this._ResourceOldestDateLastAccessedUtc = value;
                this.OnResourceOldestDateLastAccessedUtcChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.DateTimeOffset> _ResourceOldestDateLastAccessedUtc;
        partial void OnResourceOldestDateLastAccessedUtcChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnResourceOldestDateLastAccessedUtcChanged();
        /// <summary>
        /// There are no comments for Property ResourceNewestDateLastAccessedUtc in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.DateTimeOffset> ResourceNewestDateLastAccessedUtc
        {
            get
            {
                return this._ResourceNewestDateLastAccessedUtc;
            }
            set
            {
                this.OnResourceNewestDateLastAccessedUtcChanging(value);
                this._ResourceNewestDateLastAccessedUtc = value;
                this.OnResourceNewestDateLastAccessedUtcChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.DateTimeOffset> _ResourceNewestDateLastAccessedUtc;
        partial void OnResourceNewestDateLastAccessedUtcChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnResourceNewestDateLastAccessedUtcChanged();
        /// <summary>
        /// There are no comments for Property ResourceMeanDateLastAccessedUtc in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.DateTimeOffset> ResourceMeanDateLastAccessedUtc
        {
            get
            {
                return this._ResourceMeanDateLastAccessedUtc;
            }
            set
            {
                this.OnResourceMeanDateLastAccessedUtcChanging(value);
                this._ResourceMeanDateLastAccessedUtc = value;
                this.OnResourceMeanDateLastAccessedUtcChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.DateTimeOffset> _ResourceMeanDateLastAccessedUtc;
        partial void OnResourceMeanDateLastAccessedUtcChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnResourceMeanDateLastAccessedUtcChanged();
        /// <summary>
        /// There are no comments for Property ResourceTotalChangedCount in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual int ResourceTotalChangedCount
        {
            get
            {
                return this._ResourceTotalChangedCount;
            }
            set
            {
                this.OnResourceTotalChangedCountChanging(value);
                this._ResourceTotalChangedCount = value;
                this.OnResourceTotalChangedCountChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private int _ResourceTotalChangedCount;
        partial void OnResourceTotalChangedCountChanging(int value);
        partial void OnResourceTotalChangedCountChanged();
        /// <summary>
        /// There are no comments for Property ResourceMeanChangedCount in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual double ResourceMeanChangedCount
        {
            get
            {
                return this._ResourceMeanChangedCount;
            }
            set
            {
                this.OnResourceMeanChangedCountChanging(value);
                this._ResourceMeanChangedCount = value;
                this.OnResourceMeanChangedCountChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private double _ResourceMeanChangedCount;
        partial void OnResourceMeanChangedCountChanging(double value);
        partial void OnResourceMeanChangedCountChanged();
    }
    /// <summary>
    /// There are no comments for ResourceSingle in the schema.
    /// </summary>
    public partial class ResourceSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<Resource>
    {
        /// <summary>
        /// Initialize a new ResourceSingle object.
        /// </summary>
        public ResourceSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new ResourceSingle object.
        /// </summary>
        public ResourceSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new ResourceSingle object.
        /// </summary>
        public ResourceSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<Resource> query)
            : base(query) {}

    }
    /// <summary>
    /// There are no comments for Resource in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("Id")]
    public partial class Resource : global::Microsoft.OData.Client.BaseEntityType
    {
        /// <summary>
        /// Create a new Resource object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="size">Initial value of Size.</param>
        /// <param name="dateCreatedUtc">Initial value of DateCreatedUtc.</param>
        /// <param name="ageInMonths">Initial value of AgeInMonths.</param>
        /// <param name="ageInDays">Initial value of AgeInDays.</param>
        /// <param name="timestampUtc">Initial value of TimestampUtc.</param>
        /// <param name="changedCount">Initial value of ChangedCount.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public static Resource CreateResource(int ID, 
                    long size, 
                    global::System.DateTimeOffset dateCreatedUtc, 
                    int ageInMonths, 
                    int ageInDays, 
                    global::System.DateTimeOffset timestampUtc, 
                    int changedCount)
        {
            Resource resource = new Resource();
            resource.Id = ID;
            resource.Size = size;
            resource.DateCreatedUtc = dateCreatedUtc;
            resource.AgeInMonths = ageInMonths;
            resource.AgeInDays = ageInDays;
            resource.TimestampUtc = timestampUtc;
            resource.ChangedCount = changedCount;
            return resource;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property TenantId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string TenantId
        {
            get
            {
                return this._TenantId;
            }
            set
            {
                this.OnTenantIdChanging(value);
                this._TenantId = value;
                this.OnTenantIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _TenantId;
        partial void OnTenantIdChanging(string value);
        partial void OnTenantIdChanged();
        /// <summary>
        /// There are no comments for Property Path in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string Path
        {
            get
            {
                return this._Path;
            }
            set
            {
                this.OnPathChanging(value);
                this._Path = value;
                this.OnPathChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Path;
        partial void OnPathChanging(string value);
        partial void OnPathChanged();
        /// <summary>
        /// There are no comments for Property PathHash in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string PathHash
        {
            get
            {
                return this._PathHash;
            }
            set
            {
                this.OnPathHashChanging(value);
                this._PathHash = value;
                this.OnPathHashChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _PathHash;
        partial void OnPathHashChanging(string value);
        partial void OnPathHashChanged();
        /// <summary>
        /// There are no comments for Property Container in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string Container
        {
            get
            {
                return this._Container;
            }
            set
            {
                this.OnContainerChanging(value);
                this._Container = value;
                this.OnContainerChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Container;
        partial void OnContainerChanging(string value);
        partial void OnContainerChanged();
        /// <summary>
        /// There are no comments for Property ContainerHash in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string ContainerHash
        {
            get
            {
                return this._ContainerHash;
            }
            set
            {
                this.OnContainerHashChanging(value);
                this._ContainerHash = value;
                this.OnContainerHashChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _ContainerHash;
        partial void OnContainerHashChanging(string value);
        partial void OnContainerHashChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Extension in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string Extension
        {
            get
            {
                return this._Extension;
            }
            set
            {
                this.OnExtensionChanging(value);
                this._Extension = value;
                this.OnExtensionChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Extension;
        partial void OnExtensionChanging(string value);
        partial void OnExtensionChanged();
        /// <summary>
        /// There are no comments for Property Size in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual long Size
        {
            get
            {
                return this._Size;
            }
            set
            {
                this.OnSizeChanging(value);
                this._Size = value;
                this.OnSizeChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private long _Size;
        partial void OnSizeChanging(long value);
        partial void OnSizeChanged();
        /// <summary>
        /// There are no comments for Property DateCreatedUtc in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.DateTimeOffset DateCreatedUtc
        {
            get
            {
                return this._DateCreatedUtc;
            }
            set
            {
                this.OnDateCreatedUtcChanging(value);
                this._DateCreatedUtc = value;
                this.OnDateCreatedUtcChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.DateTimeOffset _DateCreatedUtc;
        partial void OnDateCreatedUtcChanging(global::System.DateTimeOffset value);
        partial void OnDateCreatedUtcChanged();
        /// <summary>
        /// There are no comments for Property AgeInMonths in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual int AgeInMonths
        {
            get
            {
                return this._AgeInMonths;
            }
            set
            {
                this.OnAgeInMonthsChanging(value);
                this._AgeInMonths = value;
                this.OnAgeInMonthsChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private int _AgeInMonths;
        partial void OnAgeInMonthsChanging(int value);
        partial void OnAgeInMonthsChanged();
        /// <summary>
        /// There are no comments for Property AgeInDays in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual int AgeInDays
        {
            get
            {
                return this._AgeInDays;
            }
            set
            {
                this.OnAgeInDaysChanging(value);
                this._AgeInDays = value;
                this.OnAgeInDaysChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private int _AgeInDays;
        partial void OnAgeInDaysChanging(int value);
        partial void OnAgeInDaysChanged();
        /// <summary>
        /// There are no comments for Property DateModifiedUtc in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.DateTimeOffset> DateModifiedUtc
        {
            get
            {
                return this._DateModifiedUtc;
            }
            set
            {
                this.OnDateModifiedUtcChanging(value);
                this._DateModifiedUtc = value;
                this.OnDateModifiedUtcChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.DateTimeOffset> _DateModifiedUtc;
        partial void OnDateModifiedUtcChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnDateModifiedUtcChanged();
        /// <summary>
        /// There are no comments for Property LastModifiedAgeInMonths in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<int> LastModifiedAgeInMonths
        {
            get
            {
                return this._LastModifiedAgeInMonths;
            }
            set
            {
                this.OnLastModifiedAgeInMonthsChanging(value);
                this._LastModifiedAgeInMonths = value;
                this.OnLastModifiedAgeInMonthsChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _LastModifiedAgeInMonths;
        partial void OnLastModifiedAgeInMonthsChanging(global::System.Nullable<int> value);
        partial void OnLastModifiedAgeInMonthsChanged();
        /// <summary>
        /// There are no comments for Property LastModifiedAgeInDays in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<int> LastModifiedAgeInDays
        {
            get
            {
                return this._LastModifiedAgeInDays;
            }
            set
            {
                this.OnLastModifiedAgeInDaysChanging(value);
                this._LastModifiedAgeInDays = value;
                this.OnLastModifiedAgeInDaysChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _LastModifiedAgeInDays;
        partial void OnLastModifiedAgeInDaysChanging(global::System.Nullable<int> value);
        partial void OnLastModifiedAgeInDaysChanged();
        /// <summary>
        /// There are no comments for Property DateLastAccessedUtc in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.DateTimeOffset> DateLastAccessedUtc
        {
            get
            {
                return this._DateLastAccessedUtc;
            }
            set
            {
                this.OnDateLastAccessedUtcChanging(value);
                this._DateLastAccessedUtc = value;
                this.OnDateLastAccessedUtcChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.DateTimeOffset> _DateLastAccessedUtc;
        partial void OnDateLastAccessedUtcChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnDateLastAccessedUtcChanged();
        /// <summary>
        /// There are no comments for Property LastAccessedAgeInMonths in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<int> LastAccessedAgeInMonths
        {
            get
            {
                return this._LastAccessedAgeInMonths;
            }
            set
            {
                this.OnLastAccessedAgeInMonthsChanging(value);
                this._LastAccessedAgeInMonths = value;
                this.OnLastAccessedAgeInMonthsChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _LastAccessedAgeInMonths;
        partial void OnLastAccessedAgeInMonthsChanging(global::System.Nullable<int> value);
        partial void OnLastAccessedAgeInMonthsChanged();
        /// <summary>
        /// There are no comments for Property LastAccessedAgeInDays in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<int> LastAccessedAgeInDays
        {
            get
            {
                return this._LastAccessedAgeInDays;
            }
            set
            {
                this.OnLastAccessedAgeInDaysChanging(value);
                this._LastAccessedAgeInDays = value;
                this.OnLastAccessedAgeInDaysChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _LastAccessedAgeInDays;
        partial void OnLastAccessedAgeInDaysChanging(global::System.Nullable<int> value);
        partial void OnLastAccessedAgeInDaysChanged();
        /// <summary>
        /// There are no comments for Property TimezoneId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string TimezoneId
        {
            get
            {
                return this._TimezoneId;
            }
            set
            {
                this.OnTimezoneIdChanging(value);
                this._TimezoneId = value;
                this.OnTimezoneIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _TimezoneId;
        partial void OnTimezoneIdChanging(string value);
        partial void OnTimezoneIdChanged();
        /// <summary>
        /// There are no comments for Property TimestampUtc in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.DateTimeOffset TimestampUtc
        {
            get
            {
                return this._TimestampUtc;
            }
            set
            {
                this.OnTimestampUtcChanging(value);
                this._TimestampUtc = value;
                this.OnTimestampUtcChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.DateTimeOffset _TimestampUtc;
        partial void OnTimestampUtcChanging(global::System.DateTimeOffset value);
        partial void OnTimestampUtcChanged();
        /// <summary>
        /// There are no comments for Property ChangedCount in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual int ChangedCount
        {
            get
            {
                return this._ChangedCount;
            }
            set
            {
                this.OnChangedCountChanging(value);
                this._ChangedCount = value;
                this.OnChangedCountChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private int _ChangedCount;
        partial void OnChangedCountChanging(int value);
        partial void OnChangedCountChanged();
    }
    /// <summary>
    /// Class containing all extension methods
    /// </summary>
    public static class ExtensionMethods
    {
        /// <summary>
        /// Get an entity of type global::ResourceCatalogApi.Models.Container as global::ResourceCatalogApi.Models.ContainerSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::ResourceCatalogApi.Models.ContainerSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::ResourceCatalogApi.Models.Container> source, global::System.Collections.Generic.IDictionary<string, object> keys)
        {
            return new global::ResourceCatalogApi.Models.ContainerSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::ResourceCatalogApi.Models.Container as global::ResourceCatalogApi.Models.ContainerSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="id">The value of id</param>
        public static global::ResourceCatalogApi.Models.ContainerSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::ResourceCatalogApi.Models.Container> source,
            int id)
        {
            global::System.Collections.Generic.IDictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "Id", id }
            };
            return new global::ResourceCatalogApi.Models.ContainerSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::ResourceCatalogApi.Models.Resource as global::ResourceCatalogApi.Models.ResourceSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::ResourceCatalogApi.Models.ResourceSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::ResourceCatalogApi.Models.Resource> source, global::System.Collections.Generic.IDictionary<string, object> keys)
        {
            return new global::ResourceCatalogApi.Models.ResourceSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::ResourceCatalogApi.Models.Resource as global::ResourceCatalogApi.Models.ResourceSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="id">The value of id</param>
        public static global::ResourceCatalogApi.Models.ResourceSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::ResourceCatalogApi.Models.Resource> source,
            int id)
        {
            global::System.Collections.Generic.IDictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "Id", id }
            };
            return new global::ResourceCatalogApi.Models.ResourceSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
    }
}
namespace Default
{
    /// <summary>
    /// There are no comments for Container in the schema.
    /// </summary>
    public partial class Container : global::Microsoft.OData.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new Container object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public Container(global::System.Uri serviceRoot) :
                base(serviceRoot, global::Microsoft.OData.Client.ODataProtocolVersion.V4)
        {
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
            this.Format.UseJson();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for Containers in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::ResourceCatalogApi.Models.Container> Containers
        {
            get
            {
                if ((this._Containers == null))
                {
                    this._Containers = base.CreateQuery<global::ResourceCatalogApi.Models.Container>("Containers");
                }
                return this._Containers;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::ResourceCatalogApi.Models.Container> _Containers;
        /// <summary>
        /// There are no comments for Resources in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::ResourceCatalogApi.Models.Resource> Resources
        {
            get
            {
                if ((this._Resources == null))
                {
                    this._Resources = base.CreateQuery<global::ResourceCatalogApi.Models.Resource>("Resources");
                }
                return this._Resources;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::ResourceCatalogApi.Models.Resource> _Resources;
        /// <summary>
        /// There are no comments for Containers in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual void AddToContainers(global::ResourceCatalogApi.Models.Container container)
        {
            base.AddObject("Containers", container);
        }
        /// <summary>
        /// There are no comments for Resources in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual void AddToResources(global::ResourceCatalogApi.Models.Resource resource)
        {
            base.AddObject("Resources", resource);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
            private static global::Microsoft.OData.Edm.IEdmModel ParsedModel = LoadModelFromString();

            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
            private const string filePath = @"Csdl.xml";

            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
            public static global::Microsoft.OData.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
            private static global::Microsoft.OData.Edm.IEdmModel LoadModelFromString()
            {
                global::System.Xml.XmlReader reader = CreateXmlReader();
                try
                {
                    global::System.Collections.Generic.IEnumerable<global::Microsoft.OData.Edm.Validation.EdmError> errors;
                    global::Microsoft.OData.Edm.IEdmModel edmModel;

                    if (!global::Microsoft.OData.Edm.Csdl.CsdlReader.TryParse(reader, false, out edmModel, out errors))
                    {
	                    global::System.Text.StringBuilder errorMessages = new System.Text.StringBuilder();
	                    foreach (var error in errors)
	                    {
		                    errorMessages.Append(error.ErrorMessage);
		                    errorMessages.Append("; ");
	                    }
	                    throw new global::System.InvalidOperationException(errorMessages.ToString());
                    }

                    return edmModel;
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }

            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
            private static global::System.Xml.XmlReader CreateXmlReader()
            {
                try
                {
                    var assembly = global::System.Reflection.Assembly.GetExecutingAssembly();
                    var resourcePath = global::System.Linq.Enumerable.Single(assembly.GetManifestResourceNames(), str => str.EndsWith(filePath));
                    global::System.IO.Stream stream = assembly.GetManifestResourceStream(resourcePath);
                    return global::System.Xml.XmlReader.Create(new global::System.IO.StreamReader(stream));
                }
                catch(global::System.Xml.XmlException e)
                {
                    throw new global::System.Xml.XmlException("Failed to create an XmlReader from the stream. Check if the resource exists.", e);
                }
            }
        }
    }
}
